apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
    environment: python-app-green
  name: hello-gitops
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-gitops
      environment: python-app-green
  template:
    metadata:
      labels:
        app: hello-gitops
        environment: python-app-green
    spec:
      containers:
        - image: hello-gitops
          name: hello-gitops
          ports:
            - name: http
              containerPort: 8050
