apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: shevdan/hello-gitops
  newTag: 582d4750c9d144e890a8d9cac0dc0112772b0c05
