apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-gitops
  name: hello-gitops
  namespace: shared-namespace
spec:
  ports:
    - name: http
      port: 8050
      targetPort: http
  selector:
    app: hello-gitops
    environment: python-app-green
  type: ClusterIP
